document.addEventListener('alpine:init',()=>{
    Alpine.data('signupform',()=>({
        username:'',
        password:'',
        passwordConfirm:'',
        belt:'',
        bio:'',
        newsletter:true,
    }))
})